name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup buildx
      uses: docker/setup-buildx-action@v3.11.1
    - name: docker login
      uses: docker/login-action@v3.6.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: build and push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      with:
        context: .
        push: true
        tags: |
                ${{secrets.DOCKERHUB_USERNAME}}/simple-webapp:${{github.SHA}}
                ${{secrets.DOCKERHUB_USERNAME}}/simple-webapp:latest
    
